// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkjnfijylewwllrliqxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ram5maWp5bGV3d2xscmxpcXhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MjgwNzIsImV4cCI6MjA2OTMwNDA3Mn0.9rnqRNXLa2w9PNaTfN5h87JlVD0gipl4C2ww2di3VeA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});